GET https://portal.azure.com/#@emishealth.com/resource/subscriptions/06b4fbeb-a0f7-4fdd-838d-c12a1f7d9f19/resourceGroups/corpupload1999/providers/Microsoft.Storage/storageAccounts/idev/overview/?comp=list&include=metadata